x-common-env-variables: &common-env-variables
  AUTH_SECRET: ${AUTH_SECRET}
  NEXTAUTH_URL_INTERNAL: ${NEXTAUTH_URL_INTERNAL}
  AUTH_URL: ${AUTH_URL}
  FUSIONAUTH_URL: ${FUSIONAUTH_URL}
  FUSIONAUTH_ISSUER: ${FUSIONAUTH_ISSUER}
  FUSIONAUTH_TENTANT_ID: ${FUSIONAUTH_TENTANT_ID}
  FUSIONAUTH_APPLICATION_ID: ${FUSIONAUTH_APPLICATION_ID}
  FUSIONAUTH_API_KEY: ${FUSIONAUTH_API_KEY}
  GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
  GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

services:
  arlo:
    build:
      context: .
      dockerfile: ./apps/arlo/Dockerfile
    environment:
      <<: *common-env-variables
      APP_NAME: arlo
      NEXT_PUBLIC_LOGIN_API: ${NEXT_PUBLIC_LOGIN_API}
      MEDIA_BACKEND_URL: ${MEDIA_BACKEND_URL}
      NEXT_PUBLIC_ARLO_BACKEND_URL: ${NEXT_PUBLIC_ARLO_BACKEND_URL}

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    environment:
      <<: *common-env-variables
      APP_NAME: auth
      ELEVAITE_HOMEPAGE: ${ELEVAITE_HOMEPAGE}
      RBAC_BACKEND_URL: ${RBAC_BACKEND_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      ORG_ID: ${ORG_ID}

  chatbot:
    build:
      context: .
      dockerfile: ./apps/chatbot/Dockerfile
    environment:
      <<: *common-env-variables
      APP_NAME: chatbot
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}

  sla_chatbot:
    build:
      context: .
      dockerfile: ./apps/sla_chatbot/Dockerfile
    environment:
      <<: *common-env-variables
      APP_NAME: sla_chatbot
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}

  contracts:
    build:
      context: .
      dockerfile: ./apps/contracts/Dockerfile
    environment:
      <<: *common-env-variables
      APP_NAME: contracts
      NEXT_PUBLIC_CONTRACTS_API_URL: ${NEXT_PUBLIC_CONTRACTS_API_URL}

  elevaite:
    build:
      context: .
      dockerfile: ./apps/elevaite/Dockerfile
    environment:
      <<: *common-env-variables
      APP_NAME: elevaite
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
      NEXT_PUBLIC_MODELS_API_URL: ${NEXT_PUBLIC_MODELS_API_URL}
      NEXT_PUBLIC_CONTRACTS_API_URL: ${NEXT_PUBLIC_CONTRACTS_API_URL}
      NEXT_PUBLIC_CONTRACTS_IOPEX_API_URL: ${NEXT_PUBLIC_CONTRACTS_IOPEX_API_URL}
      RBAC_BACKEND_URL: ${RBAC_BACKEND_URL}

  exceltoppt:
    build:
      context: .
      dockerfile: ./apps/exceltoppt/Dockerfile
    environment:
      <<: *common-env-variables
      APP_NAME: exceltoppt
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}

  media:
    build:
      context: .
      dockerfile: ./apps/media/Dockerfile
    environment:
      <<: *common-env-variables
      APP_NAME: media
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
      NEXT_PUBLIC_MEDIA_BACKEND_URL: ${NEXT_PUBLIC_MEDIA_BACKEND_URL}

  media_dashboard:
    build:
      context: .
      dockerfile: ./apps/media_dashboard/Dockerfile
    environment:
      <<: *common-env-variables
      APP_NAME: media_dashboard
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
      NEXT_PUBLIC_MEDIA_BACKEND_URL: ${NEXT_PUBLIC_MEDIA_BACKEND_URL}

  pipelines:
    build:
      context: .
      dockerfile: ./apps/pipelines/Dockerfile
    environment:
      <<: *common-env-variables
      APP_NAME: pipelines
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}

  creative_insight:
    build:
      context: .
      dockerfile: ./apps/creative_insight/Dockerfile
    environment:
      <<: *common-env-variables
      APP_NAME: creative_insight
      NEXT_PUBLIC_CREATIVE_BACKEND_URL: ${NEXT_PUBLIC_CREATIVE_BACKEND_URL}
      NEXT_PUBLIC_CREATIVE_URL: ${NEXT_PUBLIC_CREATIVE_URL}

      NEXT_PUBLIC_API_BASE_URL_SQLAGENT: ${NEXT_PUBLIC_API_BASE_URL_SQLAGENT}