# abbreviations = {
#     "ACT": "Accelerated Change Team",
#     "ACS": "Air Courier Service",
#     "AP": "Accounts Payable",
#     "AOM": "Advanced Order Management",
#     "ABC": "Activity Based Costing",
#     "4690": "Operating system unique to TGCS uniquely geared to support retail checkout environment Software",
#     "11SDOC": "One Standard-One Test, Supplier's Declaration of Conformity",
#     "2 WAY MATCH": "Invoices are matched against the Purchase Order (no Receiving is needed)",
#     "2BD": "Second business day",
#     "3 WAY MATCH": "Invoices, Purchase Orders and Received (validated) amount all must be matched before invoices can be paid.",
#     "3PL / TPL": "Third-Party Logistics",
#     "4PL / FPL": "Fourth-Party Logistics",
#     "ABS": "Air Bearing Slider",
#     "ACE": "Re-write of SA in C/C++ language. Software",
#     "ADEC": "Advance Logic ECO (for nonproduction card assembly actions). ISC",
#     "AET": "Alternate Encryption Technique",
#     "AFR": "Available for Repair / Rework / Service Parts",
#     "AFRWAC": "AFR Weighted Average Cost",
#     "ANCO": "Analyzer Code",
#     "ANN": "Official product announcement to the general public (IBM)",
#     "ANSI": "American National Standards Institute SQR",
#     "AOI": "Automated Optical Inspections PQA",
#     "APAC": "Asia Pacific and China",
#     "6200": "Tcx 800",
#     "6800": "System 7",
#     "pn": "part number",
#     "sys": "system",
#     "sco": "self checkout",
#     "fru": "field replaceable unit",
#     "4900": "Tcx 700",
# }

abbreviations = {
    "4690": "Operating system unique to TGCS uniquely geared to support retail checkout environment",
    "11SDOC": "One Standard-One Test, Supplier's Declaration of Conformity",
    "2 way match": "Invoices are matched against the Purchase Order (no Receiving is needed)",
    "2BD": "Second business day",
    "3 way match": "Invoices, Purchase Orders and Received (validated) amount all must be matched before invoices can be paid.",
    "3PL/TPL": "Third-Party Logistics",
    "4PL/FPL": "Fourth-Party Logistics",
    "AAS": "Advanced Administrative System",
    "ABC": "Activity Based Costing",
    "ABS": "Air Bearing Slider",
    "ACE": "Re-write of SA in C/C++ language.",
    "ACS": "Air Courier Service",
    "ACT": "Accelerated Change Team",
    "ADEC": "Advance Logic ECO (for nonproduction card assembly actions).",
    "AET": "Alternate Encryption Technique",
    "AFR": "Available for Repair / Rework / Service Parts",
    "AFRWAC": "AFR Weighted Average Cost",
    "ANCO": "Analyzer Code",
    "ANN": "Official product announcement to the general public (IBM)",
    "ANSI": "American National Standards Institute",
    "AOI": "Automated Optical Inspections",
    "AOM": "Advanced Order Management",
    "AP_num3": "Accounts Payable",
    "AP_num2": "Asia Pacific",
    "APAC": "Asia Pacific and China",
    "APAR": "Authorized program analysis report - request for correction of a defect in a supported release of a program.",
    "APC": "Asset Protection Class",
    "APEX": "Japanese PSCO",
    "API Date": "All-Parts-In Date",
    "APOC": "Administrative Point of Control",
    "APOF": "Automated Parts Order Form",
    "APT": "Asia-Pacific Tele community",
    "AQL": "Acceptable Quality Level",
    "AQSIQ": "State General Administration of the People's Republic of China for Quality Supervision and Inspection and Quarantine",
    "AR": "Microsoft Authorized Replicator",
    "ARA": "Alternative Resource Analysis",
    "ARB": "Architecture Review Board - A Development group that reviews and decides the direction of our products",
    "ARMS": "Automated Report Management Service",
    "ARO": "After Receipt of Order",
    "AS400": "Application System 400",
    "ASA": "Analysis Sheet Adjustment",
    "ASCA": "Application Systems Control & Auditability",
    "ASL": "Alternate Stock Level",
    "ASL_num2": "Approved Supplier List",
    "ASM_num2": "Area Security Manager",
    "ASQC": "American Society for Quality Control",
    "ASSD": "Actual Supplier Ship Date",
    "ASTAP": "Asia-Pacific Tele community Standardization Program",
    "ASW": "Approvals Summary Worksheet",
    "ATB": "Available to Balance",
    "ATD": "Asset Tracking Database",
    "ATP": "Available to Promise",
    "ATS": "Korean Agency for Technology and Standards",
    "AVL": "Approved Vendor List",
    "B&SD": "GSL Business & Systems Development",
    "B2B": "Business To Business",
    "B2C": "Business To Consumer",
    "BA": "Business Analyst",
    "BAC": "Business Application Code",
    "BAU": "Business as Usual",
    "BBFV": "Building block functional validation?",
    "BC": "Business Controls",
    "BCP": "Business Continuity Plan",
    "BD": "Blue Desk (the Legacy IBM tool for Purchase requisitions)",
    "BDSC": "Big Data Supply Chain",
    "BIOS": "Basic Input Output System - refers to firmware that controls initial booting of system units and provides interfaces to the hardware for HW drivers.",
    "BIS": "Business Innovation Services",
    "BLE": "Business Line Executive",
    "BLM": "Business Line Manager",
    "BMC": "Base Manufacturing Cost",
    "BMWB": "Business Manager's Workbench",
    "BO": "Branch Office",
    "BOD": "Branch Office Directory",
    "BOM": "Bill of Material",
    "BOP": "Business Optimization Program",
    "BP": "Business partner",
    "BPA": "Blanket Purchase Agreement (Oracle PO type) goods/svcs/pricing defined for time period - issue Purchase Releases against the BPA",
    "ΒΡΟ": "Business Process Owner",
    "BPR": "Business Process Re-Engineering",
    "BRIC": "Brazil, Russia, India, China",
    "BRM": "Business Review Meeting",
    "BSC": "Business Support Center (UPS)",
    "BSOD": "Blue screen of death",
    "BSTD": "Beistandard, Balarus PSCO",
    "BU": "Business Unit",
    "BW": "Blue Works",
    "C2C": "Cash Conversion Cycle",
    "CA": "Controlled Area",
    "CA_num2": "Conformity Assessment",
    "CA_num3": "Contracts Administrator",
    "CABLELABS": "Cable Laboratories",
    "CAC": "Customer Assistance Center (IBM's name for the Ops Buying Team)",
    "CANIETI": "Mexican PSCO",
    "CAP": "Central Asset Protection",
    "CAPRI": "Common Accounts Payable & Receiving Verification Information",
    "Card EMI": "Early Mfg Involvement (provided by Procurement)",
    "CAS": "CPPS Authorization System",
    "CAS_num2": "Controlled Area Security",
    "CATS": "Critical (Corporate) Asset Tracking System",
    "CB": "Central Buffer",
    "CB_num2": "Certification Body",
    "CBT": "Computer Based Training",
    "CC": "Compliance Coordinator",
    "CCC": "China Compulsory Certification",
    "CCEE": "Chinese Certification Committee for Electrical Engineering Products",
    "CCIB": "Chinese Commodity Inspection Bureau",
    "CCR": "Contract Change Request",
    "CCSA": "China Communications Standards Association",
    "CD_num2": "Cash Drawer",
    "CDA": "Confidential Disclosure Agreement = see/use MNDA",
    "CDC": "Country Distribution Center",
    "CDRH": "Center for Devices and Radiological Health (USA)",
    "CDW": "Client Data Warehouse",
    "CE": "Customer Engineer",
    "CE_num2": "Marking of Conformity to European Directives",
    "CED": "Central Emergency Desk",
    "CEH": "Customer Engineer Hours",
    "CESAL": "Customer Engineering Stock Action Letter",
    "CESAR": "CPPS, SAP & RAP",
    "CESIS": "Customer Engineering Service Information System",
    "CFE": "Customer Furnished Equipment",
    "CFOC": "Corporate Focal Point",
    "CFR": "Code of Federal Regulations (USA)",
    "CHQ": "Corporate Headquarters",
    "CI_num2": "Corporate Instruction",
    "CIAS": "Common Intercompany Accounting System",
    "CIC": "Credit Invoice Control",
    "CIF": "Cost, Insurance, and Freight",
    "CIX": "Commercial Internet Exchange",
    "CI-100": "Compliance",
    "CLARS": "CPPS Local Asset Reporting System",
    "CLC": "Commodity Logistic Center",
    "CM": "Contract Mfg (e.g. Celestica, Jabil)",
    "CM_num2": "Category Manager",
    "CM_num3": "Commodity Manager",
    "CMC": "Call Management Center",
    "CMR": "Change Management Request",
    "CMR_num2": "Customer Master Record",
    "CMT": "Complaint Management Tool",
    "CMT_num2": "Change Management Team",
    "CN": "Contracts Negotiator",
    "CNC": "Computerized Numerical Control",
    "CNCA": "China National regulatory commission for Certification and Accreditation",
    "COA": "Certificate of Authorization",
    "COA_num2": "Certificate of Authenticity = labels which must be placed onto TGCS HW containing MS embedded products",
    "COD": "Confirmation of Delivery",
    "COINS": "Cost of Inventory System",
    "ColP": "Conferencing over IP",
    "COL": "Change of Location",
    "COO": "Certificate Of Originality, to be filled in by internal and external HW and SW providers, legal stuff",
    "COO_num2": "Certificate of Originality. Contract attachment provided to Suppliers of developed works whereby they certify the originality/ownership of the developed works or elements.",
    "CORS": "CPPS Off-Line RH & SE",
    "COS": "Customer Owned Stock",
    "CP": "Corporate Procedure",
    "CPA": "Contracts Purchase Agreement",
    "CPF": "Central Planning File",
    "CPFR": "Collaborative Planning Forecasting and Replenishment",
    "CPL": "Components Placement List",
    "CPPS": "Common Parts Process System",
    "CQ": "ClearQuest, a defect tracking tool",
    "CQC": "China Quality Certification Center",
    "CR": "Cash Receipt, usually implies cash receipt station",
    "CR_num2": "Central Repair / Change Request",
    "CR_num3": "Change Request",
    "CRA": "Control Risk Analysis",
    "CRAD": "Customer Requested Arrival Date",
    "CRH": "Central Request Handling",
    "CRIT": "Client Research and Innovation Team",
    "CRL": "Central Repair Location",
    "CRM": "Customer Relationship Management",
    "CRS": "Committed Recovery Service",
    "CRU": "Customer Replaceable Unit",
    "CRV": "Central Repair Vendor",
    "CS": "Corporate Standard",
    "CSA": "Canadian Standards Association",
    "CSA_num2": "Continuous Self Assessment (See also MSA)",
    "CSA_num3": "Country Standards Authority",
    "CSCMP": "Council of Supply Chain Management Professionals",
    "CSG": "Central (Country) Support Group",
    "CSL": "Country Stock Location",
    "CSO": "Customer Support Organization",
    "CSP": "Certified Spare Parts",
    "CSP_num2": "Certified Service Product",
    "CSP_num3": "Certified Service Product (Service Parts)",
    "CSPO": "customer satisfaction project office",
    "CSR": "Country (Central) Stock Room",
    "CSR_num2": "Customer Service Representative",
    "CSR_num3": "Corporate Social Responsibility",
    "CSS": "Customer Support System",
    "CSS_num2": "Core Sameday Store",
    "CSW": "Completed Staff Work",
    "CT": "Compliance Test / Control Tower",
    "CT_num2": "Cost Take Out (for Cost Savings)",
    "CTB": "Clear To Build",
    "CTP": "Comprehensive Test Plan",
    "CV": "Cash Value",
    "CVP": "Configuration Verification Program",
    "CWF": "Complementary Work Force / Contingent Workforce",
    "D&S": "Distribution and Support",
    "D2D": "Demand to Deliver",
    "DACS": "Direct Asset Control System",
    "DAM": "Data Management",
    "DART": "Data Access & Reporting Tool",
    "DAU GREEN": "Demand Acceleration Unit-early ship product can be sold",
    "DAU RED": "Demand Acceleration Unit-beta ship must be returned",
    "DB": "Database",
    "DBOR": "Direct Branch Office Replenishment",
    "DC": "Distribution Center",
    "DCF": "Decentralize File",
    "DCG": "Delivery Competence Group",
    "DCP": "Decision Checkpoint",
    "DCP_num2": "Decision Control Point",
    "DCS": "Direct Customership (Previous Ndd)",
    "DCS_num2": "Distributed Control System",
    "DCT": "Development Core Team",
    "DE or DEV": "Development Engineering",
    "DEMCO": "Denmark PSCO",
    "DER": "Daily Exception Report",
    "DES": "Data Encryption Standard/System",
    "DEV": "Development",
    "DFF": "Descriptive Flex Field",
    "DFI": "Defect Free Install (actually covers initial 30 days after install)",
    "DFI_num2": "Defective Parts Inventory",
    "DFM": "Design for Mfg Rep (role of the Procurement EMI Reps)",
    "DGN": "Direction General de Normas",
    "DGR": "Daily Going Rate",
    "DHL": "DHL Solutions, the Managing Distribution Vendor",
    "DI": "Document Insert, usually implies Document Insert Station",
    "DICOM": "Digital Imaging and Communication in Medicine",
    "DIMM": "Dual In-line Memory Module",
    "DIS": "Draft International Standard",
    "DLS": "Distribution Logistics System",
    "DMD": "Digital Media Distribution",
    "DMI": "Distributor-managed Inventory",
    "DNCI": "Argentina Direction of Internal Trade",
    "DOA": "Dead on Arrival",
    "DoC": "Declaration of Conformity",
    "DOM": "Department Operating Manual",
    "DOU": "Document of Understanding",
    "DPF": "Document Publishing Facility",
    "DPL": "Denied Parts List",
    "DPL_num2": "Denied Parties List",
    "DPM": "Development Project Manager",
    "DPMS": "Distribution Planning & Management System",
    "DPRS": "Development & Production Records System",
    "DPRS_num2": "Data Parts Retrieval System",
    "DRP": "Distribution Requirements Planning",
    "DRR": "Design Readiness Review",
    "DSA": "Distribution Stock Action",
    "DSR": "Demand Signal Repository",
    "DTD": "Day To Day delta in orders",
    "DVM": "Digital Voltmeter",
    "DVT": "Test Result",
    "DVT_num2": "Design Verification Test",
    "DWA": "Developed Works Agreement",
    "DWC": "Dealer Warranty Claim",
    "DWH": "Dealer Warranty Handler",
    "E Model": "Refers to model number of Windows preloaded machines. For example: 4800-E85, 4852-E26.",
    "E2E": "End To End",
    "EAN": "International Article Number",
    "EAU": "Estimated Annual Usage",
    "EBS": "Enterprise Business Suite (Oracle EBS)",
    "EC": "Engineering Change",
    "EC_num2": "European Commission",
    "EC Prototype": "Engineering Change Prototype",
    "EC Tracker": "Engineering Change Tracker",
    "ECA": "ECO Analyzer",
    "ECA_num2": "Engineering Change Announcements",
    "ECAT": "Electronic Card Assembly and Test",
    "ECCC": "Electronic Commerce Council of Canada",
    "ECCN": "Export Control Classification Number",
    "ECD": "Exceeding Count Difference",
    "ECECP": "Engineering Center Environmentally Conscious Products",
    "ECN": "Engineering Change Notice / Notification",
    "ECO": "Engineering Change Order",
    "ECO_num2": "Environmental Careers Organization",
    "ECOWAC": "Economic Weighted Average Cost",
    "ECP": "Environmentally Conscious Products",
    "ECPOC": "Engineering Change Point of Control",
    "ECRB": "Engineering Change Review Board",
    "ECRC": "EC Reason Code",
    "EDI": "Electronic Data Interchange",
    "EEC": "European Economic Community",
    "EEPROM": "Electrically Erasable Programmable Read-Only Memory",
    "EET": "Engineering Effective Tracker",
    "EGI": "EGI.net Procurement tool for ECO electronic data exchange with Suppliers.",
    "EHQ": "European Headquarters",
    "EIC": "European Information Center",
    "EID": "Enterprise Identification. This is the ID which is assigned for partners/suppliers who need to access our systems. ITHelp \"provisions\" these to individuals and typically need a \"sponsor\" who is a TGCS employee",
    "EID_num2": "Enterprise Identification",
    "EIP": "Early Involvement Program",
    "EIP_num2": "Enterprise Interplant Process",
    "ELMEX": "Element Exchange",
    "ELP": "Early Life Performance",
    "ELR": "Early Life Reliability",
    "EMARS": "Environmental Material Aggregation & Reporting System",
    "EMC": "Enterprise Management Center",
    "EMEA": "Europe, Middle-East & Africa",
    "EMET": "Engineering Maintenance Effectiveness Test",
    "EMF": "Electromagnetic Fields",
    "EMI": "Early Manufacturing Involvement",
    "EMLS": "Enterprise Materials Logistics System",
    "EN": "European Norm",
    "EO": "Emergancy Order",
    "EOD": "Emergency Order Desk",
    "EOL": "End of Life",
    "EOM": "End of Marketing (Manufacturing)",
    "EOP": "End of Production",
    "EOP/M": "End-of-Production/Marketing",
    "EOQ": "Economic Order Quantity",
    "EOR": "Emergency Order Referral",
    "EOS": "End of Service",
    "EPL": "Electronic Price Letter",
    "EPOC_num2": "Education Point of Control",
    "EPOM": "External Plant of Manufacturing",
    "EPRG": "Enterprise Parts Requirement Generation",
    "EPSC": "Emergency Parts Support Centers",
    "ERE": "Enterprise Repository Environment (Corp db/tool for ECO tech data).",
    "ERP": "Emergancy response Planning",
    "ERS": "Emergency Referral System",
    "ES": "Enterprise Systems",
    "ESAK": "Electric Safety Association of Korea",
    "ESD": "Enterprise Solution Deployment",
    "ESD_num2": "Electro Static Discharge",
    "ESDP": "EMEA Service Delivery Project, Planning",
    "ESL": "EMEA Service Logistics",
    "ESO": "External Sales Orders",
    "ESP": "Early Support Program",
    "ESP_num2": "Early Ship Program",
    "ESPD": "EMEA Service Parts Delivery",
    "ESPL": "EMEA Spare Parts List",
    "ESPRIT": "EMEA Service Planning & Reference & Information Tool",
    "ESZ": "Excess, Surplus and Scrap",
    "ETA": "Estimated Time of Arrival (of a Part at the Shipment Address)",
    "ETL": "Extract Transform and Load",
    "ETN": "Equivalent to New",
    "ETN_num2": "Equal to New",
    "EUCS": "End User Computing Service",
    "EVPU": "Slovakian PSCO",
    "ExCo": "Executive Committee of the ANSI Board of Directors",
    "EZU": "Czech Republic NCB/PSCO",
    "FA": "Financial Analyst / Finance Analyst",
    "FA_num2": "Failure Analysis",
    "FAF": "First available Flight",
    "FAI": "first article inspection",
    "FAN": "Financial Analysis",
    "FAP": "FRU and Production Part",
    "FBM": "Field Bill of Material",
    "FCL": "Full Container Load",
    "FCS": "First Customer Ship or Floor Control System",
    "FCS_num2": "First Customer Shipment",
    "FCS_num3": "First Customer Shipment of a product (IBM)",
    "FCT": "Functional Card/Component Test",
    "FD": "Functional Design",
    "FDM": "FRU Data Management",
    "FDW": "Financial Data Warehouse",
    "FFBM": "Field Feature Bill of Material",
    "FFC": "Fulfillment Center",
    "FFI": "Field Feature Index",
    "FIC": "Framework for Internal Controls",
    "FIFO": "First In/First Out",
    "FIW": "Financial Information Warehouse",
    "FMCG": "Fast Moving Consumer Goods",
    "FOB": "Free On Board",
    "FOC": "Focal Point",
    "FOE": "Firm Order Exception - soft order",
    "FOEC": "Formal ECO (used when ADECS/RLECs are n/a)",
    "FOU": "Financial Organization Unit",
    "FPA": "First Parts Analysis",
    "FPA_num2": "Field Parts Advocate",
    "FPY": "First Pass Yield (measured at the Tier 2 suppliers)",
    "FRR": "Fulfillment Readiness Review",
    "FRS": "Free Re-Distributable Stock",
    "FRU": "Field Replaceable Unit",
    "FSI": "Financial Services International",
    "FST": "Final System Test",
    "FST_num2": "Function/System Test",
    "FTAA": "Free Trade Area of the Americas",
    "FTS": "Field Technical Support",
    "FU": "Fiscal Unit",
    "FUM": "Field Use Materials",
    "FV": "Fair Value",
    "FVA": "Forecast Value Add Analysis",
    "FVT": "Functional Verification Test",
    "FW": "Firmware, Devices using firmware = printers, keyboards, touch panels,",
    "FW/REV": "Forward and Reverse",
    "GA": "General Availability",
    "GARR": "GA Readiness Review",
    "GARS": "Global Asset Recovery Services",
    "GCM": "Global Commodity Manager",
    "GEIA": "Government Electronics & Information Technology",
    "GEO": "Geography",
    "GES": "Ventura (Box Supplier)",
    "GGS": "Geodis Global Solutions",
    "GL": "Global Logistics",
    "GLB": "Global Logistics Benelux",
    "GLDG": "Global Logistics Development Group",
    "GMCF": "Global Mobile Commerce Forum",
    "GOE": "Global Offering Executive",
    "GOG": "Glass On Glass",
    "GPM": "Global Procurement Manager",
    "GPS": "Global Parts System",
    "GS": "Gerpruefte Sichereit (approved safety)",
    "GS1": "Global Standards 1",
    "GSA": "General Sales Application. CBASIC. Geared toward department store environment",
    "GSC": "Global Standards Collaboration",
    "GSL": "Global Service Logistics",
    "GSM MoU": "Global System for Mobile Communication Memorandum of Understanding",
    "GSTD-R": "Gosstandard of Russia, Russian PSCO",
    "GTM": "Global Trade Management",
    "GUI/UI": "Graphical User Interface / User Interface",
    "GVR": "Gross Variance Report",
    "H/W": "Hardware",
    "HA-API": "Human Authentication Application Programming Interface",
    "HANA": "High Performance Analytic Appliance",
    "HAVI": "Home Audio Video Interoperability",
    "HDD": "Hard Disk Drive",
    "HIPPA": "Health Insurance Portability and Accountability Act",
    "HLD": "High-Level Design",
    "HMI": "Human Machine Interface",
    "HPS": "High Productivity Screens",
    "HUN": "Jabil Hungary",
    "HW": "Hardware",
    "I/O": "Input/Output devices",
    "I S": "install & service",
    "I2O": "Idea to Opportunity",
    "IBB": "Installed Base Breakdown",
    "IBF": "International Banking Facility",
    "IBM": "International Business Machines",
    "IBN": "Belgian Institute for Standardization",
    "IBP": "Initial Business Plan",
    "IBS": "IBM Business School",
    "IC": "Inventory Control",
    "ICA": "Inter-Company Agreement",
    "ICBP": "Inter Company Billing Price",
    "ICP": "Inductively Coupled Plasma",
    "ICT": "information & communication technology",
    "ICT_num2": "In-Circuit Test",
    "IDDE": "International Distribution & Data Exchange",
    "IDS": "IBM Parts Distribution System",
    "IECEE": "IEC System for confirmity testing to standards for safety of electronic equipment",
    "IESC": "Inter-Enterprise System Connection",
    "IGS": "IBM Global Services",
    "ILAS": "International Logistics and Services BV",
    "i-listed RPQ": "RPQ owner needed to approve RPQ",
    "IMD": "IBM Microelectronics Division",
    "IMPL": "International Maintenance Parts Logistics",
    "IMR": "Inventory Management Report",
    "IMS": "Information Management System",
    "IN": "Incident Number (as in the IN against the SR Ticket)",
    "INMETRO": "Instituto Nacional de Metrologia, Normalização e Qualidade Industrial",
    "IO/SBP": "Initial Offering / Solution Business Plan",
    "IP": "Intellectual Property",
    "IPD": "Integrated Product Development",
    "IPF": "Integrated Project File",
    "IPLS": "Interplant Parts Logistics System",
    "IPM": "Initial Parts Management",
    "IPMT": "Integrated Portfolio Management Team",
    "IPODC": "(No full form provided in the document for IPODC)",
    "IPP": "Integrated Project Plan",
    "IPP_num2": "Individual Picking Point",
    "IPP_num3": "Internet Printing Protocol",
    "IPR": "Inter-Plant Requisition, Inter-Plant Parts Requisition",
    "IPROC": "iProcurement",
    "IQC": "Incoming Quality Control",
    "IR": "Improvement Request",
    "IRB": "Investment Review Board",
    "ISAS": "International Sales and Services BV",
    "ISC": "Integrated Supply Chain w/ engineering manufacturing technical team - ME, QE, TE",
    "ISD": "Item Synchro Date",
    "ISM": "Institute for Supply Management",
    "ISO": "International Standards Organization",
    "ISO_num2": "Internal Sales Orders",
    "ISP": "Initial Spare Part",
    "ISU": "Industry Solution Unit",
    "ISV": "Independent Service Vendor",
    "IT test": "Independent Test",
    "IT": "Information Technology",
    "ITI": "Czech Republic Institute of Technical Inspection",
    "ITS": "Information Technology Services",
    "ITS_num2": "Integrated Technology Services",
    "ITS_num3": "Intertek Testing Services",
    "ITS_num4": "Intelligent Transportation Systems",
    "ITU-T": "Telecommunication Standardization Sector",
    "IVT": "Invoice Verification Tool",
    "IWA": "International Workshop Agreement",
    "IX-Retail": "International XML Retail Cooperative",
    "JCMT": "Joint Crisis Management Team",
    "JDA": "Joint Disclosure Agreement (see/use MNDA)",
    "JET": "Japanese NCB / PSCO",
    "JH": "Jabil Hungary",
    "JIT": "Just-in-Time Inventory",
    "JM": "Jabil Memphis",
    "JMI": "Joint-Managed Inventory",
    "JOP": "Jumping Off Point (baseline for reporting)",
    "JQA": "Japanese NCB/PSCO",
    "JRS": "Job Release Supervisor",
    "JW": "Jabil Wuxi",
    "KBA": "Knowledge based articles",
    "KCC": "knowledge consistency checker",
    "KETI": "Korea Electro-Electric Testing Institute",
    "KOF": "Kit Order Form",
    "KOS": "Keep on Stock",
    "KPM": "Key Performance Measurement",
    "KTL": "Korea Testing Laboratory",
    "L/F": "Lead free",
    "LA": "Latin America",
    "LAT": "Latin America",
    "LATS": "Local Asset Tracking System",
    "LCD": "Liquid Crystal Display",
    "LCL": "Less than Container Load",
    "LCM": "Life Cycle Management",
    "LDG": "Logistic Development Group",
    "LDTS": "Loss & Damage Tracking System",
    "LEI": "Logistics Early Involvement (also known as ELI)",
    "LIFO": "Last In, First Out",
    "LIMS": "Laboratory Information Management System",
    "LMT": "Lifecycle Management Team",
    "LNDB": "Lotus Notes Database",
    "LOA": "Letter of Agreement",
    "LOA_num2": "Letter of Authorization",
    "LOD": "Last Order Date",
    "LOV": "List of Values",
    "LP": "Location Planning",
    "LPA": "Link pack area portion of virtual storage below 16 MB that contains frequently used modules.",
    "LPS": "Local Parts Support",
    "LRR": "Launch Readiness Review",
    "LS": "Logistics Solution, Learning Services",
    "LSA": "Logical Systems Architecture",
    "LSF": "Local Support Function",
    "LSH": "Local Stocking HUB",
    "LSO": "Local Support Organization",
    "ILSP": "Logistic Service Provider",
    "LSPR": "Local Spare Parts List",
    "LSS": "GLB Logistics Systems Support",
    "LT": "Lead time",
    "LTB": "Last Time Buy",
    "LTC": "Linux Technology Center, provide MCP operating system to TGCS",
    "LTL": "Less-Than-Truckload",
    "LWA": "Licensed Works Agreement (old, legacy Agreement we use MPA now)",
    "M&D": "Manufacturing and Design/Development",
    "M/T": "Machine Type",
    "MA": "Maintenance Agreement",
    "MAC": "Media Access Control (Address)",
    "MAC_num2": "Move Add Change (Telecom, offices)",
    "MAPICS": "Manufacturing, Accounting and Production Information Control System",
    "Marcom": "Market Communications",
    "MAS": "Multivendor Availability Services",
    "MAT": "Machine Analysis Table",
    "MBG": "IBM Mechanicsburg",
    "MBWA": "Managing by Walking Around",
    "MCDA": "Mutual Confidential Disclosure Agreement (aka MNDA)",
    "MCO": "Manufacturer's Certificate of Origin",
    "MCP": "Micro Control Program, Embedded Linux OS provided by LTC to TGCS.",
    "MD": "Master Data",
    "MDRR": "Manufacturing & Development Readiness Review",
    "ME": "Manufacturing Engineer",
    "MEEI": "Hungarian PSCO",
    "MEM": "Jabil Memphis",
    "MES": "Miscellaneous Equipment Spec-Hardware",
    "MES_num2": "Manufacturing Equipment Specification",
    "MES_num3": "Manufacturing Engineering System",
    "MES_num4": "Miscellaneous Equipment Specification",
    "MET": "United States NCB / PSCO",
    "MET_num2": "Maintenance Effectiveness Test",
    "MFC": "Memory Flow Controller",
    "MFC_num2": "Machine Feature Code",
    "MFG": "Manufacturing",
    "MFI": "Machine Feature Index",
    "MFI_num2": "Manufacturing Feature Index",
    "MGED": "Microarray Gene Expression Data Society",
    "Mgr": "Manager",
    "MH": "Materials Handling",
    "MISC": "Miscellaneous",
    "MIW": "Multivendor Information Warehouse",
    "MNDA": "Mutual Non-Disclosure Agreement",
    "MOP": "IBM Montpellier",
    "MOQ": "Minimum Order Quantity",
    "MOU": "Memorandum of Understanding",
    "MP": "Market Planning",
    "MP_num2": "Macro Point",
    "MPA": "Master Procurement Agreement",
    "MPC": "Maintenance Parts Cost",
    "MPM": "Manufacturing Program Manager",
    "MPM_num2": "Multivendor Product Management",
    "MPQA": "Master Product Quality Agreement",
    "MRA": "Mutual Recognition Agreement",
    "MRB": "Material Review Board",
    "MRP": "Materials Requirement Planning",
    "MRR": "Manufacturing Readiness Review",
    "MS": "Microsoft",
    "MS_num2": "Microsoft or Management Server - systems management software runs on.",
    "MSA": "Management Self Assessment (See also CSA)",
    "MSA_num2": "Master Services Agreement (old, legacy agreement we use MPA now)",
    "MSD": "Mositure Sensitive Devices",
    "MSDS": "Material Safety Data Sheet",
    "MSL": "Minimum Ship Level",
    "MSOW": "Master Statement of Work",
    "MSP": "Managed Service Provider",
    "MSP_num2": "Microsoft Project",
    "MSP Association": "Management Service Provider Association",
    "MSR": "Magnetic Stripe Reader",
    "MSS": "Micro Sameday Store",
    "MSS_num2": "Management System Standards",
    "IMT": "Machine Type",
    "MTBF": "Mean Time Between Failure",
    "MTL": "Material",
    "MTM": "Machine Type Model",
    "MTM_num2": "Month To Month",
    "MTS": "Marketing Technical Support, Group interfacing with retail customers, entry point for problem reporting, Group presenting conferences and classes to our customers",
    "MTS EMEA SPO": "Maintenance and Technical Support, Europe, Middle East and Africa Service Parts Operation",
    "MV": "Managing Vendor",
    "MVA": "Material Value Add",
    "MVP": "Master Validation Plan",
    "MVS": "Multi Vendor Support/Services",
    "MVT": "Manufacturing Verification Test",
    "NA": "North America",
    "NATA": "National Association of Testing Authorities (Australia)",
    "NBD": "Next Business Day",
    "NCB": "National Certification Body",
    "NCM": "Non-Conforming Material",
    "INDA": "Non-Disclosure Agreement (see/use MNDA)",
    "NDD": "Next Day Delivery",
    "INDF": "No Defect Found",
    "NDSEA": "Non Development Solutions Engagement Agreement (old, legacy Agreement - we use MPA now)",
    "NEC": "National Electrical Code (NFPA 70)",
    "NF": "Non Ferro",
    "NHD": "Networking Hardware Division",
    "NIP": "Non IBM Product",
    "NLS": "National Language Support",
    "NN": "Network Neighbourhood",
    "NOM": "Norma Oficial Mexicana Mexican official standard",
    "NP": "New Products",
    "NPAC": "National Parts Administration Center",
    "NPI": "New Product Introduction",
    "INPII": "New Products Introduction Implementation",
    "NPP": "New Products Planning",
    "NRE": "Non-Reocurring Engineering (A one time cost)",
    "NRF": "National Retail Federation (Major Retailer Group)",
    "NRND": "Not Recommended for New Designs",
    "NRSC": "National Retail Services Center",
    "NRTL": "Nationally Recognized Testing Laboratory certified by OSHA for the USA",
    "NSC": "National Support Center",
    "NSP": "Non Standard Parts",
    "NSSN": "ANSI National Resource for Global Standards",
    "INTE": "Not to exceed",
    "NTTAA": "National Technology Transfer and Advancement Act",
    "NVRAM": "Nonvolatile Random Access Memory - retains contents after power shut off.",
    "NYCE": "Normalizacion Y Certificacion Electronica",
    "O/SBP": "Offering/ Solution Business Plan",
    "02D": "Order To Delivery",
    "02Q": "Opportunity to Quote",
    "OAA": "El Organismo Argentino de Acreditación",
    "OBA": "Operational balancing agreement",
    "OBD": "Order Booked Date",
    "OBI": "Open Buying on the Internet",
    "OBI_num2": "Oracle Business Intelligence",
    "OBIEE": "Oracle Business Intelligence Enterprise Edition",
    "OCI": "Other Concerned Individual",
    "OCN": "Order Creation Date",
    "ODL": "Operational Data Layer",
    "OEE": "Overall Equipment Effectiveness",
    "OEM": "Original Equipment Manufacturer",
    "OH": "Order Handling",
    "OHR": "Order Handling Review",
    "OHSMS": "Occupational Health and Safety Management System Standards",
    "OL": "Outside Location (Expense or Inventory)",
    "OMF": "ANSI's Organizational Member Forum",
    "OMG-LSR": "Object Management Group",
    "00": "Oppurtunity Owner",
    "OOW": "Out of Warranty",
    "OP": "Output",
    "ORT": "On-Going Reliability Test",
    "OS": "Operating System",
    "OSC": "Outsourced Supply Chain",
    "OSHA": "Occupational Safety and Health Administration (USA)",
    "OSM": "Outsource Manufacturing",
    "OSR": "Outstanding Return",
    "OSS": "On-Site Support",
    "OSV": "OEM Software View-5th day of month nonTN COA label",
    "OSVTN": "Combines OSV & TN Reports",
    "OU": "Organization, Operation Unit",
    "OU_num2": "Operating Unit / Country",
    "P&L": "Profit and Loss",
    "PA": "Participation Agreement. Contract attachment or exhibit to MPA which allows for other entities/subsidiaries/affiliates to be participants to the MPA; typically used to add the European or APAC affiliate to the MPA between TGCS Inc. and SupplierUSA. Example: Zebra/Motorola US and TGCS Inc have a base Agreement; there are 20+ PA's for Canada, UK, Spain, China, etc.",
    "PAL": "Parts Availability Level",
    "PANDA": "Parts Analysis Development Application",
    "PBL": "Performance Based Logistics",
    "PBS": "Planning Business Support",
    "PCBA": "Printed Circuit Board Assembly",
    "PCBC": "Polish NCB/PSCO",
    "PCD": "Process Customization Declaration",
    "PCD_num2": "Product Content Declaration",
    "PCD_num3": "Procurement Code",
    "PCE": "Product Cost Estimate",
    "PCN": "Process Change Notice",
    "PCR": "Plan Change Request",
    "PCR_num2": "Project Change Request",
    "PDA": "Product Documentation Analyst",
    "PDC": "Parts Delivery Criteria",
    "PDI": "Product data Interface",
    "PDM": "Product Data Management",
    "PDM II": "Personal Development Manager",
    "PDS": "Product Detail Sheet",
    "PDT": "Project Development Team",
    "PDT_num2": "Product Development Team",
    "PDT Lead": "Person who owns the business side of several HW and SW projects",
    "PDW": "Process Data Warehouse",
    "PE": "Product Engineer / Engineering",
    "Pends": "Orders Requested in a time period we can't ship",
    "PEP": "Product Environmental Profile",
    "PEW": "Product Entitlement Warranty",
    "PEW_num2": "PCD Entitlement Warehouse",
    "PFE": "Product Field Engineer",
    "Phase C": "Client Delay",
    "Phase D": "Root Cause know and fix being investigated/created in Development",
    "Phase I": "Implementation",
    "Phase M": "Monitor",
    "Phase U": "Unknown Root Cause",
    "PIE": "Parts Information Exchange",
    "PII": "Program Integrated Information",
    "PIMS": "Project Investment Management System",
    "PIMS_num2": "Parts Inventory Management System",
    "PIV": "Physical Inventory Verification",
    "PLCM": "TSS EMEA SPO Product Life Cycle Management",
    "PLD": "(No full form provided in the document for PLD)",
    "p-listed RPQ": "RPQ is available for ordering",
    "PLM": "Product Lifecycle Management",
    "PM": "Project Manager",
    "PMC": "Production Management Center",
    "PMH": "Problem management hardware",
    "PMO": "Project Management Office",
    "PMR": "Problem management record number that represents a service incident with a customer.",
    "PN": "Part Number",
    "pn" : "Part Number",
    "PO": "Standard PO (Oracle PO Type) - defined goods/services/pricing for a specific purchase",
    "POD": "Proof of Delivery",
    "POK": "IBM Poughkeepsie",
    "POS": "Point of Sales",
    "POS Printer": "Point Of Sale Printer, Designed, built, and supported by TGCS",
    "POSCO": "(No full form provided in the document for POSCO)",
    "POSReady 2009": "Viewed as WEPOS Version 2.0, an embedded Windows OS, a Windows XP variant",
    "POSReady 7": "An embedded Window OS, a Windows 7 variant",
    "PPA": "Product Line Profitability Analysis",
    "PPM": "Parts Per Millon",
    "PPML": "Personalized Print Markup Language",
    "PPN": "Production Part Number",
    "PPT": "Parts Procurement Time",
    "PQA": "Product Quality Addendum",
    "PQC": "Product Quality Council",
    "PQC II": "Parts Quality Coordinator",
    "PQE": "Procurement Quality Engineer",
    "PR": "Purchase Requisition",
    "Preload": "Refers to TGCS offering of Windows operating systems preloaded on system unit",
    "Prestops": "Quality Issue where action is required but does not miss customer shipments",
    "PRF": "Parts Return Form",
    "PRF_num2": "Pre-Requisition Form used to facilitate sourcing and procurement activities",
    "PRG": "Parts Requirements Generation Program",
    "PRMA": "Parts Requiring Management Attention",
    "PSA": "Product Safety Authority",
    "PSC": "Printing Systems Company",
    "PSC_num2": "Product Safety Coordinator",
    "PSCO": "Product Safety Certification Organization",
    "PSD": "Planned ship date",
    "PSD_num2": "Possible Ship Date",
    "PSD_num3": "IBM Printing Service Division, Parts Supply Determination",
    "PSE": "Preliminary sales estimate",
    "PSE_num2": "Product Safety Engineer",
    "PSG": "Personal Systems Group",
    "PSI": "Print Services Interface",
    "PSP": "Preferred Service Provider",
    "PSPA": "Program Standards Project Authority",
    "PSR": "Parts Supply Request",
    "PSRB": "Product Safety Review Board",
    "PSSD": "Planned supplier ship date",
    "PSTN": "Public Switched Telephone Network",
    "PTB": "Product Take Back",
    "PTO": "Pick to Order",
    "PTR": "Premium Transportation Request",
    "PUA": "Product Unique Attachement (old legacy agreement - Use SOW now)",
    "PUDO": "PickUp Dropoff Point",
    "PV": "Process Variable",
    "PVA": "Procurement Value Add (for cost savings)",
    "PWA": "Physical Warehouse Access",
    "Q2C": "Quote to Commitment",
    "QA": "Quality Assurance",
    "QAS": "Quality Assurance Services (Australia",
    "QBR": "Quarterly Business Review",
    "QCS": "Quality Controls System",
    "QE": "Quality Engineering",
    "QEV": "Quarterly Employee Verification",
    "QIN": "Quality Information Network",
    "QMF": "Query Management Facility",
    "QMS": "Quality Management System",
    "QMX": "IBM Global Management System, could be explained as Quality 9000 (Q for Quality, X with overscore = 10,000, minus M=1,000)",
    "QMX_num2": "Quality Management System",
    "QPA": "Quality Production Audit (LSP Internal Quality Test)",
    "QR": "Quality Review",
    "QRQC": "(No full form provided in the document for QRQC)",
    "R&D": "Research & Development",
    "R&TTE": "Radio and Telecommunications Terminal Equipment",
    "R2R": "Record to Report",
    "RA": "Repair Action measure of repairs on machines in field in first year after install (30 days self)",
    "RA_num2": "Repair Activity, Risk Assessment",
    "RA/MM": "Repair Actions per Machine Month",
    "RA/MY": "Repair Actions per Machine Year",
    "RADT": "Requested Arrival Date Time",
    "RAR": "Repair Action Record",
    "RARA": "Risk Assessment, Risk Acceptance",
    "RAS": "Reliability, availability, serviceability",
    "RASSQM": "Reutilization Basic Data",
    "RBD": "(No full form provided in the document for RBD)",
    "RCM": "Regulatory Compliance Mark (Australia)",
    "RCMS": "Retain-Linked Call Management System",
    "RD": "Request Date",
    "REA": "Request for Engineering Action",
    "REF": "Reference",
    "REOL": "Reorder Level",
    "RETAIN": "A problem reporting and tracking system for field/customer reported problems",
    "REUT": "Re-Utilization",
    "RFA": "Release for Announcement",
    "RFI": "Request for Information",
    "RFID": "Radio Frequency Identification",
    "RFP": "Request for Proposal",
    "RFPV": "Request for Price Verification",
    "RFQ": "Request for Quote",
    "IRFS": "Ready for Announcement",
    "RFx": "Term used to refer to a family of 'Request For...' documents used to solicit responses of various types from suppliers. The three most commonly used documents in this family include Request for Information (RFI), Request for Quote (RFQ), and Request for Proposal (RFP)",
    "RH": "Request Handling",
    "RH/CED": "TSS EMEA SPO Request Handling / Central Emergency Desk",
    "RI": "Receiving Inspection",
    "RIA": "Request for Immediate Approval",
    "RIC": "Rotating Inventory Count",
    "RISC": "Reduced Instruction Set Computer",
    "RLEC": "Relevel ECO (used as the roll up ECO for previous ADECs. This is the Card's Formal ECO when ADECS were utilized).",
    "RM": "Relationship Manager",
    "RMA": "Remote Management Application/process geared toward managing hardware and software remotely. unattended.",
    "RMA_num2": "Return Material Authorization",
    "RMAR": "Returned Material and Adjustment Request",
    "RMC": "Resource Management Center",
    "RMDS": "Report Management Display System",
    "RO": "Region Office",
    "ROE": "Regional Offering Executive",
    "ROI": "Return On Investment",
    "ROM": "Reutilization Opportunity Management",
    "RPL": "Restricted Party List",
    "RPMES": "Returned Parts Miscellaneous Equipment Specification",
    "RPQ": "Request for Price Quotation",
    "RPS": "Restricted Party Screening",
    "RRF": "Repository Request Form",
    "RRS": "Receipt (Receiving) and Returns System",
    "RSD": "Request Ship Date",
    "RSH": "RSH = Regional Stocking HUB",
    "RSL": "Recommended Stock Level",
    "RSS": "Retail Store Solutions",
    "RSS_num2": "Retail Support Services",
    "RSSD": "Requested Supplier Ship Date",
    "RT": "Req Tracker (Their workflow/collaboration tool between Ops Buyers & TBs)",
    "RTC": "Rational Team Concert, a development process tracking tool",
    "RTM": "Release to Manufacture",
    "RTM_num2": "Routes to Market",
    "RTM_num3": "Recovery Termination Manager",
    "RTP": "Research Triangle Park (NC)",
    "RTS": "Ready to Ship (PGI@Jabil)",
    "S&OP": "Sales and Operations Planning",
    "S&U": "Returns",
    "S/N": "Serial Number (also SN)",
    "S/W": "Software",
    "SA": "Supermarket Application, Legacy application originally in our own programming language, CBASIC.",
    "SA_num2": "Stock Allocation",
    "SAA": "Stabilization and Association Agreement",
    "SaaS": "Software as a Service",
    "SAC": "Supplier Availability Category",
    "SACA": "Semi-Annual Control Assessment (Not Applicable Any More)",
    "SAD": "Scheduled Arrival Date",
    "SAP": "System Applications and Products",
    "SASO": "Saudi Arabian Standards Organization",
    "SB": "SB Strategy Board",
    "SBS": "System Business Support",
    "SC": "Subcommittee",
    "SCE": "Service Cost Estimate",
    "SCF": "Stock Correction Form",
    "SCM": "Supply Chain Management",
    "SCO": "Self-Checkout",
    "SCOR": "Supply Chain Operations Reference",
    "SCRL": "Standards Compliance Reference List",
    "SCS": "Storage Cloud Services",
    "SCS_num2": "Supply Chain Solutions",
    "SD": "Shipped Date",
    "SDO": "Standards Developing Organization",
    "SDOC": "Supplier's Declaration of Conformity",
    "SDS": "Shipment Documentation System, Same Day Stock",
    "SDV": "System Design Verification",
    "SE": "Supply Execution",
    "SEA": "Solutions Engagement Agreement (old, legacy Agreement - we use MPA now)",
    "SFD": "Source File Database",
    "SGA": "Selling General Administrative",
    "SGE": "Jabil Hungary",
    "SGS": "Solectron Global Services",
    "SGW": "Jabil Wuxi",
    "SI": "System Integration",
    "SIC": "Standard Industry Classification",
    "SID": "supplier initiation date",
    "SIOP": "Sales Inventory Operations and Planning",
    "SIQ": "Slovenian PSCO",
    "SIR": "Security Incident Report",
    "SISIR": "Singapore Institute of Standards and Industrial Research",
    "SIT": "System integration test",
    "SKU": "Stock-keeping Unit",
    "SL3": "(No full form provided in the document for SL3)",
    "SLA": "Service Level Agreement",
    "SLBM": "Service Logistics Business Manager",
    "SLM": "Service Logistics Management Module",
    "SLPM": "Service Logistics Product Manager",
    "SM&E": "TSS EMEA SPO Source Management & Engineering",
    "SME": "Subject Matter Expert",
    "SMI": "Supplier Managed Inventory",
    "SMT": "Supervised Manufacturing Test",
    "SMU": "Shippable Manufacturing Units",
    "SN": "Serial Number",
    "SO": "Strategic Outsourcing",
    "SOD": "Separation of Duties",
    "SOP": "Standard Operating Procedure",
    "SOR": "Statement of Requirements",
    "SOS": "System Operating System",
    "SOVP": "Start of Volume Production",
    "SOW": "Statement of Work",
    "SOX": "Sarbanes Oxley",
    "SP": "Set Point",
    "SP_num2": "SurePOS, as in SP 100, SP 300, SP 500, SP 700",
    "SPA": "Standards Project Authority (IBM)",
    "SPA_num2": "Standards Project Authority",
    "SPAN": "Strategic Position Analysis",
    "SPC": "Statistical Process Control",
    "SPD": "Sensitive Parts Database",
    "SPI": "Solder Paste Inspection",
    "SPI_num2": "Shipping Procedural Instructions",
    "SPIF": "Short Product Information File",
    "SPL": "Supplier Problem Log",
    "SPL_num2": "Spare Parts List",
    "SPM": "Special Product Marketing",
    "SPO": "Service Parts Operations",
    "SPOC": "Single Point Of Contact",
    "SPOE": "Single Point of Entry",
    "SPQ": "Ship Pack Quantity",
    "SPQL": "Shipped Product Quality Level (aka IQL)",
    "SPR": "Service Planning Representative",
    "SPRING": "Singapore Standards, Productivity and Innovation Board",
    "SPSP": "Service parts supply plan",
    "Spt": "Support",
    "SQA": "Stock Quantity Adjustment",
    "SQC": "Statistical Quality Control",
    "SQD": "Supplier Quality Document",
    "SQMS2": "Supplier Quality Management System 2",
    "SQR": "Supplier Quality Requirements",
    "SR": "Supply Request",
    "SR_num2": "Service Request (as in SR Ticket for an IT issue/question)",
    "SRF": "Sourcing Request Form - refers to the SharePoint tool / Custom Form develop to operationalize the PRF",
    "SRM": "Supplier Relationship Management",
    "SRR": "System Requirement Review",
    "SRTS": "Software Royalty Tracking System",
    "SS": "Sourcing Specialist - Regional Sourcing, Contracting, Negotiation. Builds relationships with Suppliers, Ops buyers, and business areas.",
    "SS_num2": "Support Station / Sameday Store",
    "SSAC": "Stratetgic Sourcing Advisory Council",
    "SSD": "Solid State Drive",
    "SSD_num2": "Scheduled Ship Date -external sales order",
    "SSD_num3": "Storage System Division",
    "SSI": "Sales Support Information",
    "SSPM": "Senior Spare Parts Management, Manager, Meeting",
    "SSR": "Software specification review - in waterfall life cycle, the major review held when the software requirements specification is complete.",
    "SSR_num2": "Stagnant Request Report - email generated by the SRF tool sent to procurement management team so that they can take action. Report items have aged or have become stagnant for more that 48Hr from being submiited",
    "SSS": "Super Sameday Store",
    "SST": "Steady State Team (Department within OSC)",
    "ST": "Start To build",
    "ST_num2": "SameTime (aka: Chat Tool or Instant Messaging)",
    "STB": "Start To Build",
    "STC": "Singapore Trading Company",
    "STC_num2": "Service the Customer",
    "STCR": "(No full form provided in the document for STCR)",
    "STR": "Stretch (For Goals)",
    "STSM": "Senior Technical, Executive level technical people",
    "SUVA": "Swiss Federal Inspectorate for Work Accidents",
    "Svc/Spt": "Service/Support",
    "SVT": "System Verification Test",
    "SW": "Software",
    "T&C": "Terms & Conditions",
    "T&H": "Temperaute and Humidity",
    "TAG": "Technical Advisory Group",
    "TAT": "Turn around Time",
    "TB": "Tactical Buyer",
    "TBD": "To Be Determined",
    "TBT": "WTO Agreement on Technical Barriers to Trade",
    "TC": "Technical Committee",
    "TCA": "German PSCU & Notified Body that may issue GS marks",
    "TCM": "Terminal Condition Models",
    "TCO": "Total Cost of Ownership",
    "TCV": "Total Contract Value",
    "TDO": "Table of Denial Order",
    "TE": "Test Engineer",
    "TGCS": "Toshiba Global Commerce Solutions",
    "THOR": "Total Hardware Order Repository",
    "T13": "(No full form provided in the document for T13)",
    "TIE": "TEC manf in Indoiense",
    "TIN": "Tracking Identification Number",
    "TMC": "Total Manufacturing Cost",
    "TMS": "Transportation Management System",
    "TN": "Thumb nail report-3rd day of month COA TN",
    "TP": "Transitional Phase / ThinkPad",
    "TPLC": "Total Parts Logistics Cost",
    "TPM": "Technical Program Manager",
    "TPM_num2": "Technical Performance Measures",
    "TPM_num3": "Third Party Maintenance",
    "ΤΡΟ": "Test Purposes Only",
    "TQA": "Technology Qualification Application",
    "TQM": "Total Quality Management",
    "TSA": "Technical Services Agreement (old, legacy Agreement we use MPA now)",
    "TSACC": "Telecommunications Standards Advisory Council of Canada",
    "TSDB": "Tool Summary Database",
    "TSE": "TTEC Manufacturing in Singapore",
    "TSE_num2": "Technical Sales Enablement",
    "TSM": "Total Systems Management",
    "TSO": "Time Sharing Option",
    "TSP": "(No full form provided in the document for TSP)",
    "TSS": "Technical Support Services",
    "TTA": "Telecommunications Technology Association",
    "TÜV": "German PSCO & Notified Body that issues GS marks",
    "TVT": "Translation Verification Test",
    "UAT": "User Acceptance Testing",
    "UCC": "Uniform Code Council (United States)",
    "UCD": "User Centered Design",
    "UCI": "Used Parts Return Control Instruction",
    "UCL": "Used Class",
    "UCM": "Unit Cost Model",
    "UkrSEPRO": "Ukranian Certification System",
    "UL": "Underwriter's Laboratories",
    "ULT": "Useful Life Test",
    "UPC_num2": "Universal Product Code",
    "UPK": "User Productivity kit",
    "UPOS": "Unified Point Of Sale drivers. A standard for POS I/O APIs. TGCS has own version of UPOS implementation in the form of OPOS and JavaPOS.",
    "UPR": "Used Parts Returnable",
    "UPR_num2": "Used Part Return",
    "UPS": "Uninterruptible Power System",
    "USA": "United States of America",
    "USB": "Universal Serial Bus",
    "USF": "United States (Sales Country)",
    "USF_num2": "United States Finished Goods",
    "USM": "United States Manufacturing",
    "USP": "Jabil Memphis",
    "USSS": "US Single Source",
    "USTR": "United States Trade Representative",
    "UUID": "Universally Unique Identifier",
    "UUT": "Unit Under Test",
    "V11": "V11 Form (request form used to set up New Supplier or update Existing Supplier record/info)",
    "VA": "Visual Aids",
    "VAR": "Value Added Reseller",
    "VAT": "Value Added Tax",
    "VDE": "German NCB / PSCO & Notified Body that may issue GS marks",
    "IVFD": "Vacuum Fluorescent Display",
    "VIC": "Vendor Invoice Control",
    "VIE": "Vendor Invoice Entry",
    "VIS": "Vendor Invoicing System",
    "VIW": "Variance Investigation Worksheet",
    "VLH": "Vendor Loop Hardware Products (non-TGCS products)",
    "VM": "Virtual Machine",
    "VMI": "Vendor-Managed Inventory",
    "VMM": "(No full form provided in the document for VMM)",
    "VPD": "Vital Product",
    "VPM": "Vendor Performance Management",
    "VXIbus": "VXIbus Consortium",
    "WAC": "Weighted Average Cost",
    "WD": "Western Digitial",
    "WDFM": "Withdrawn From Marketing",
    "WEPOS": "Windows Embedded Point Of Service, an embedded Windows OS, a Windows XP variant",
    "WG": "Working Group",
    "Windows 7 FES": "Windows 7 For Embedded Systems, full Windows 7 distribution for the embedded space",
    "Windows XP FES": "Windows XP For Embedded Systems, full Windows XP distribution for embedded space",
    "WIP": "Work In Progress",
    "WM": "Withdrawn From Market",
    "WMS": "Warehouse Management System",
    "WOI": "Web Order & Invoice",
    "WTAM": "World Trade Accounting Manual",
    "Wuxi": "Jabil Wuxi",
    "ww": "World Wide",
    "WWDC": "World Wide Data Collect",
    "WWDM": "World Wide Data Management",
    "WWPD": "World Wide Parts Database",
    "X.org": "X.org",
    "XBRL": "Extensible Business Reporting Language",
    "bat": "battery",
    "batt": "battery",
    "asy": "assembly",
    "bkt": "bracket",
    "WLMT": "Walmart",
    "KRG": "Kroger",
    "KRGR": "Kroger",
    "DRW": "Drawer",
    "REV": "Revision",
    "INCL": "Includes",
    "DISP": "Display",
    "Mon": "Monitor",
    "UNIV": "Universal",
    "NTWK": "Network",
    "CNTRL": "Controller",
    "PWR": "Power",
    "SUP": "Supply",
    "PC": "Personal Computer",
    "AV": "Audio Video",
    "TSC": "Tractor Supply Company",
    "TS": "Tractor Supply",
    "TV": "Television",
    "AP": "Access Pointe",
    "CD": "Cash Drawer",
    "PRN": "Printer",
    "SFF": "small form factor",
    "WNTY": "Warranty",
    "Mono": "monochrome",
    "UPC": "Universal Product Code",
    "ADPTR": "Adapter",
    "APPL": "Appliance",
    "PCB": "printed circuit board",
    "IG": "iron gray (may not always be the case but is likely the case)",
    "M TOLE": "Mettler Toledo",
    "INTF": "Interface",
    "MTOLE": "Mettler Toledo",
    "INTERS": "Interstate Battery",
    "BELK": "Belkin",
    "LENV": "Lenovo",
    "MON": "Monitor",
    "MON LENV": "Monitor Lenovo",
    "OKI": "Okidata",
    "Lexmark": "Lexmark",
    "HP": "Hewlett Packard",
    "CTG": "Cables to go",
    "GB": "Gigabyte",
    "MB": "Megabyte",
    "SILV": "Silver",
    "BLK": "Black",
    "LVD": "Low Voltage Disk",
    "SPEAKR": "Speaker",
    "ASM": "Assembly",
    "PCI": "Peripheral Component Interconnect",
    "V2": "Version 2",
    "ASY": "assembly",
    "SARC": "Sarcomm",
    "WLG": "Walgreens",
    "WGN": "Walgreens",
    "WMT": "Walmart",
    "SLO": "Service Level Objective",
    "DASD": "Direct Acccess Storage Device",
    "DDR": "double data rate",
    "CPU": "central processer unit",
    "proc": "microprocessor",
    "op panel": "operator panel",
    "COM": "Communication",
    "Thx": "Thanks",
    "HDR": "Hard Drive Retention",
    "T&T": "Training & Tasks (Costco)",
    "T&M": "Time & Materials",
    "ACC": "Accessory",
    "IF": "Interface",
    "IPL": "initial program load",
    "SENT": "Sentry (scanner scales)",
    "HT": "Harris Teeter",
    "HH": "Handheld",
    "EPSN": "Epson",
    "FSL": "Forwards Stocking Locaion",
    "PIR": "Passive Infared",
    "LLT": "Platter (scanner scale)",
    "FXD": "Fixed (scanner scale)",
    "M98": "9800i scanner scale",
    "CI": "Configuration Item (Tractor Supply Company)",
    "Mid-flight": "TSC only; depot and customer; ups scans part @ honeywell and must get old part back in;",
}

MACHINE_ABBREVIATIONS = \
    {'2001': {'001': 'TCX M1'},
    '2011': {'100': 'TCX M11'},
    '4612': {'All': 'SurePoint Mobile', 'C01': 'SurePoint Mobile', 'D01': 'SurePoint Mobile', 'L01': 'SurePoint Mobile', 'P01': 'SurePoint Mobile'},
    '4613': {'xx8': 'SurePOS 100', '108': 'SurePOS 100', 'E18': 'SurePOS 100', 'EA8': 'SurePOS 100', 'A18': 'SurePOS 100'},
    '4614': {'Oxx': 'SureOne', '1xx': 'SureOne', 'A0x': 'SureOne', 'P8x': 'SureOne', 'SOx': 'SureOne', 'SPx': 'SureOne', 'V0x': 'SureOne', 'V8x': 'SureOne'},
    '4615': {'C0x': 'SureOne', 'J0x': 'SureOne'},
    '4674': {'All': '4674 (AP only)'},
    '4683': {'All': '4683'},
    '4693': {'All': '4693'},
    '4694': {'All': '4694'},
    '4695': {'All': '4695'},
    '4750': {'D10': 'Toshiba Basics'},
    '4800': {'0xx': 'SureBase', '1xx': 'SurePOS 730', '7xx': 'SurePOS 700', '2xx': 'SurePOS 750', '7x1': 'SurePOS 700', '7x2': 'SurePOS 700', '7x3': 'SurePOS 700', '7x4': 'SurePOS 700'},
    '4810': {'31x': 'SurePOS 300', '32x': 'SurePOS 300', '33x': 'SurePOS 300', '34x': 'TCX300', '35x': 'TCX300', '3x0': 'TCX300', '3x1': 'TCX300'},
    '4818': {'3x1': 'Toshiba Basics T10', 'x10': 'Toshiba Basics T10'},
    '4825': {'x4x': 'TCX 620'},
    '4828': {'x2x': 'TCx 810 Essential'},
    '4835': {'All': 'NetVista Kiosk'},
    '4836': {'1xx': 'Anyplace Kiosk'},
    '4838': {'1xx': 'Anyplace Kiosk', '3xx': 'Anyplace Kiosk', '5xx': 'Anyplace Kiosk', '7xx': 'Anyplace Kiosk', '9xx': 'Anyplace Kiosk'},
    '4840': {'xx1': 'SurePOS 500', 'xx2': 'SurePOS 500', 'xx3': 'SurePOS 500', 'xx4': 'SurePOS 500'},
    '4845': {'1xx': 'IBM Self Checkout', 'Nxx': 'IBM Self Checkout', 'Exx': 'IBM Self Checkout', 'Xxx': 'IBM Self Checkout', '6xx': 'IBM Self Checkout', '8xx': 'IBM Self Checkout', 'Bxx': 'IBM Self Checkout', 'Ixx': 'IBM Self Checkout', '7xx': 'IBM Self Checkout', 'Wxx': 'IBM Self Checkout', 'Kxx': 'IBM Self Checkout'},
    '4846': {'xx5': 'SurePOS 500'},
    '4851': {'x14': 'SurePOS 500'},
    '4852': {'xx6': 'SurePOS 500', 'x7x': 'SurePOS 500'},
    '4855': {'xxE': 'Anyplace Checkout'},
    '4888': {'Exx': 'System 6', 'BW4': 'System 6'},
    '4900': {'7x5': 'SurePOS 700', '7x6': 'TCX 700', '7x7': 'TCX 700'},
    '4901': {'x1x': 'TCx 900'},
    '4910': {'Exx': 'SurePOS 300 Express bundle'},
    '6140': {'1xx': 'TCxWave', 'x3x': 'TCxWave', 'x4x': 'TCxWave', 'x5x': 'TCxWave'},
    '6183': {'2xx': 'TCx Flight'},
    '6200': {'1xx': 'TCx 800'},
    '6201': {'All': 'TCx 810'},
    '6225': {'All': 'TCx 820'},
    '6700': {'100': 'MXP Vison Kiosk'},
    '6800': {'1xx': 'System 7', '2xx': 'System 7', '3xx': 'MxP Self Checkout 810', '4xx': 'MxP Self Checkout 820', 'KDU': 'System 7 Kit of Parts', 'Kxx': 'MxP Self Checkout'},
    '6900': {'1xx': 'Pro-X Hybrid Kiosk'},
    '7054': {'All': 'Personal Shopper'},
    '8368': {'All': '8368 s'},
    '4610': {'Txx': 'SureMark printer', '1xx': 'Fiscal printer', '2xx': 'SureMark printer', 'Gxx': 'Fiscal printer', 'Kx6': 'Fiscal printer', 'Sxx': 'Fiscal printer'},
    '4679': {'Wxx': '4679 POS Printer (AP only)', 'Gxx': '4679 POS Printer (AP only)', '3xx': 'Fiscal printers'},
    '4685': {'Kxx': 'Keyboards (AP only)', 'Cxx': 'Cash drawer (AP only)', 'S01': 'Scanners (AP only)', 'S02': 'Scanners (AP only)', 'P04': 'Scanners (AP only)', 'L0A': 'Scanners (AP only)', 'L0F': 'Scanners (AP only)', 'L0H': 'Scanners (AP only)', 'L0C': 'Scanners (AP only)'},
    '4698': {'101': 'Scanners (AP only)', '201': 'Scanners (AP only)', '102': 'Scanners (AP only)', '202': 'Scanners (AP only)'},
    '4689': {'All': 'Thermal receipt+journal printer (AP only)'},
    '4820': {'46x': 'SurePoint Display', '48x': 'SurePoint Display', '8Bx': 'SurePoint Display', '42T': 'SurePoint Display', '42D': 'SurePoint Display', '4xx': 'SurePoint Display', 'FBD': 'SurePoint Display', '4xR': 'SurePoint Display', '1xx': 'SurePoint Display', '2xx': 'SurePoint Display', '5xx': 'SurePoint Display', 'xxB': 'SurePoint Display', '21x': 'SurePoint Display', '2Dx': 'SurePoint Display', '51x': 'SurePoint Display', '5Dx': 'SurePoint Display', '2Ax': 'SurePoint Display', '2Lx': 'SurePoint Display', '2Nx': 'SurePoint Display', '5Ax': 'SurePoint Display', '5Lx': 'SurePoint Display', '5Nx': 'SurePoint Display'},
    '6145': {'1xx': 'TCx Printer', '2xx': 'TCx Printer', '5Cx': 'TCx Display'},
    '6149': {'1xx': 'TCx Printer', '2xx': 'TCx Printer', '5Cx': 'TCx Display', '5Nx': 'TCx Display', '5Sx': 'TCx Display', 'Bxx': 'TCx Display', 'Wxx': 'TCx Display'},
    '6150': {'x1x': 'TCx Touch Display'},
    '6160': {'00x': 'TCx Edgecam (produce recognition camera)'},
    '6180': {'Sxx': 'S10 Cube printer'},
    '6260': {'00x': 'TCx Edgecam+ (loss prevention camera)'},
    '9338': {'All': 'TABS barcode printer'},
    }


ABBREVIATION_TABLE = """
| Machine Type | Model | Name |
|---|---|---|
| 2001 | 001 | TCX M1 |
| 2011 | 100 | TCX M11 |
| 4612 | All | SurePoint Mobile |
| 4612 | C01 | SurePoint Mobile |
| 4612 | D01 | SurePoint Mobile |
| 4612 | L01 | SurePoint Mobile |
| 4612 | P01 | SurePoint Mobile |
| 4613 | xx8 | SurePOS 100 |
| 4613 | 108 | SurePOS 100 |
| 4613 | E18 | SurePOS 100 |
| 4613 | EA8 | SurePOS 100 |
| 4613 | A18 | SurePOS 100 |
| 4614 | Oxx | SureOne |
| 4614 | 1xx | SureOne |
| 4614 | A0x | SureOne |
| 4614 | P8x | SureOne |
| 4614 | SOx | SureOne |
| 4614 | SPx | SureOne |
| 4614 | V0x | SureOne |
| 4614 | V8x | SureOne |
| 4615 | C0x | SureOne |
| 4615 | J0x | SureOne |
| 4674 | All | 4674 (AP only)|
| 4683 | All | 4683 |
| 4693 | All | 4693 |
| 4694 | All | 4694 |
| 4695 | All | 4695 |
| 4750 | D10 | Toshiba Basics |
| 4800 | 0xx | SureBase |
| 4800 | 1xx | SurePOS 730 |
| 4800 | 7xx | SurePOS 730 |
| 4800 | 2xx | SurePOS 750 |
| 4800 | 7xx | SurePOS 700 |
| 4800 | 7x1 | SurePOS 700 |
| 4800 | 7x2 | SurePOS 700 |
| 4800 | 7x3 | SurePOS 700 |
| 4800 | 7x4 | SurePOS 700 |
| 4810 | 31x | SurePOS 300 |
| 4810 | 32x | SurePOS 300 |
| 4810 | 33x | SurePOS 300 |
| 4810 | 34x | TCX300 |
| 4810 | 35x | TCX300 |
| 4810 | 3x0 | TCX300 |
| 4810 | 3x1 | TCX300 |
| 4818 | 3x1 | Toshiba Basics T10 |
| 4818 | x10 | Toshiba Basics T10 |
| 4825 | x4x | TCX 620 |
| 4828 | x2x | TCx 810 Essential |
| 4835 | All | NetVista Kiosk |
| 4836 | 1xx | Anyplace Kiosk |
| 4838 | 1xx | Anyplace Kiosk |
| 4838 | 3xx | Anyplace Kiosk |
| 4838 | 5xx | Anyplace Kiosk |
| 4838 | 7xx | Anyplace Kiosk |
| 4838 | 9xx | Anyplace Kiosk |
| 4840 | xx1 | SurePOS 500 |
| 4840 | xx2 | SurePOS 500 |
| 4840 | xx3 | SurePOS 500 |
| 4840 | xx4 | SurePOS 500 |
| 4845 | 1xx | IBM Self Checkout |
| 4845 | Nxx | IBM Self Checkout |
| 4845 | Exx | IBM Self Checkout |
| 4845 | Xxx | IBM Self Checkout |
| 4845 | 6xx | IBM Self Checkout |
| 4845 | 8xx | IBM Self Checkout |
| 4845 | Bxx | IBM Self Checkout |
| 4845 | Ixx | IBM Self Checkout |
| 4845 | 7xx | IBM Self Checkout |
| 4845 | Wxx | IBM Self Checkout |
| 4845 | Kxx | IBM Self Checkout |
| 4846 | xx5 | SurePOS 500 |
| 4851 | x14 | SurePOS 500 |
| 4852 | xx6 | SurePOS 500 |
| 4852 | x7x | SurePOS 500 |
| 4855 | xxE | Anyplace Checkout |
| 4888 | Exx | System 6 |
| 4888 | BW4 | System 6 |
| 4900 | 7x5 | SurePOS 700 |
| 4900 | 7x6 | TCX 700 |
| 4900 | 7x7 | TCX 700 |
| 4901 | x1x | TCx 900 |
| 4910 | Exx | SurePOS 300 Express bundle |
| 6140 | 1xx | TCxWave |
| 6140 | x3x | TCxWave |
| 6140 | x4x | TCxWave |
| 6140 | x5x | TCxWave |
| 6183 | 2xx | TCx Flight |
| 6200 | 1xx | TCx 800 |
| 6201 | All | TCX 810 |
| 6225 | All | TCX 820 |
| 6700 | 100 | MXP Vison Kiosk |
| 6800 | 1xx | System 7 |
| 6800 | 2xx | System 7 |
| 6800 | 3xx | MxP Self Checkout 810 |
| 6800 | 4xx | MxP Self Checkout 820 |
| 6800 | KDU | System 7 Kit of Parts |
| 6800 | Kxx | MxP Self Checkout |
| 6900 | 1xx | Pro-X Hybrid Kiosk |
| 7054 | All | Personal Shopper |
| 8368 | All | 8368 s|
| 4610 | Txx | SureMark printer |
| 4610 | 1xx | Fiscal printer |
| 4610 | 2xx | SureMark printer |
| 4610 | Gxx | Fiscal printer |
| 4610 | Kx6 | Fiscal printer |
| 4610 | Sxx | Fiscal printer |
| 4679 | Wxx | 4679 POS Printer (AP only) |
| 4679 | Gxx | 4679 POS Printer (AP only) |
| 4679 | 3xx | Fiscal printers |
| 4685 | Kxx | Keyboards (AP only) |
| 4685 | Cxx | Cash drawer (AP only) |
| 4685 | S01 | Scanners (AP only) |
| 4685 | S02 | Scanners (AP only) |
| 4685 | P04 | Scanners (AP only) |
| 4698 | 101 | Scanners (AP only) |
| 4698 | 201 | Scanners (AP only) |
| 4698 | 102 | Scanners (AP only) |
| 4698 | 202 | Scanners (AP only) |
| 4685 | L0A | Scanners (AP only) |
| 4685 | L0F | Scanners (AP only) |
| 4685 | L0H | Scanners (AP only) |
| 4685 | L0C | Scanners (AP only) |
| 4689 | All | Thermal receipt+journal printer (AP only) |
| 4820 | 46x | SurePoint Display |
| 4820 | 48x | SurePoint Display |
| 4820 | 8Bx | SurePoint Display |
| 4820 | 42T | SurePoint Display |
| 4820 | 42D | SurePoint Display |
| 4820 | 4xx | SurePoint Display |
| 4820 | FBD | SurePoint Display |
| 4820 | 4xR | SurePoint Display |
| 4820 | 4xx | SurePoint Display |
| 4820 | 1xx | SurePoint Display |
| 4820 | 2xx | SurePoint Display |
| 4820 | 5xx | SurePoint Display |
| 4820 | 1xx | SurePoint Display |
| 4820 | 2xx | SurePoint Display |
| 4820 | 5xx | SurePoint Display |
| 4820 | xxB | SurePoint Display |
| 4820 | 21x | SurePoint Display |
| 4820 | 2Dx | SurePoint Display |
| 4820 | 51x | SurePoint Display |
| 4820 | 5Dx | SurePoint Display |
| 4820 | 2Ax | SurePoint Display | 
| 4820 | 2Lx | SurePoint Display |
| 4820 | 2Nx | SurePoint Display |
| 4820 | 5Ax | SurePoint Display |
| 4820 | 5Lx | SurePoint Display |
| 4820 | 5Nx | SurePoint Display |
| 6145 | 1xx | TCx Printer |
| 6145 | 2xx | TCx Printer |
| 6145 | 5Cx | TCx Display |
| 6149 | 1xx | TCx Printer |
| 6149 | 2xx | TCx Printer |
| 6149 | 5Cx | TCx Display |
| 6149 | 5Nx | TCx Display |
| 6149 | 5Sx | TCx Display |
| 6149 | Bxx | TCx Display |
| 6149 | Wxx | TCx Display |
| 6150 | x1x | TCx Touch Display |
| 6160 | 00x | TCx Edgecam (produce recognition camera) |
| 6180 | Sxx | S10 Cube printer |
| 6260 | 00x | TCx Edgecam+ (loss prevention camera) |
| 9338 | All | TABS barcode printer |
"""
