import type { Metadata } from "next";
import { AppHeader } from "@repo/ui/components";
import "../ui/globals.css";
import "@repo/ui/styles.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "../../auth";

const headerButtons: { label: string; link: string; key: string }[] = [
  { key: "dashboard", label: "Dashboard", link: "/dashboard" },
  { key: "knowledge", label: "Knowledge Base", link: "/kb" },
  { key: "functions", label: "Functions", link: "/functions" },

  { key: "apps", label: "Apps", link: "/homepage" },
  { key: "users", label: "Users", link: "/users" },
  { key: "configurations", label: "Configurations", link: "/configurations" },
];
export const metadata: Metadata = {
  title: "AI Deck Builder by elevAIte",
  description: "Generated by create next app",
};

export default async function HomepageLayout({
  children,
}: {
  children: React.ReactNode;
}): Promise<JSX.Element> {
  const session = await auth();
  if (session?.user) {
    // filter out sensitive data before passing to client.
    session.user = {
      id: session.user.id,
      name: session.user.name,
      email: session.user.email,
      image: session.user.image,
    };
  }
  return (
    <SessionProvider session={session}>
      <div className=" w-screen h-screen">
        <AppHeader buttons={headerButtons}>{children}</AppHeader>
      </div>
    </SessionProvider>
  );
}
